# Generated by Django 4.1.4 on 2022-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
    ]
