name: Python CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # if  you want to test yr app on several versions of Python, just add them to list
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run test and linter
        run: make check
        env:
          SECRET_KEY: secret
      - name: Publish code coverage report
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          SECRET_KEY: secret
          CC_TEST_REPORTER_ID: ${{secrets.TEST_COVERAGE}}
        with:
          coverageCommand: make test-coverage
